name: Release
on:
    push:
        tags:
            - "v*"
    workflow_dispatch:

jobs:
    release:
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-latest, ubuntu-20.04, windows-latest]
        runs-on: ${{ matrix.platform }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-20.04'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev

            - name: Rust setup
              uses: dtolnay/rust-toolchain@stable

            - name: Rust cache
              uses: swatinem/rust-cache@v2
              with:
                  workspaces: "./src-tauri -> target"

            - name: Sync node version and setup cache
              uses: actions/setup-node@v3
              with:
                  node-version: "lts/*"
                  cache: "npm"

            - name: Install app dependencies and build web
              run: npm install && npm run build

            - name: Build the app
              uses: tauri-apps/tauri-action@v0

              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tagName: ${{ github.ref_name }}
                  releaseName: "v__VERSION__"
                  releaseBody: "Aniluv release draft."
                  releaseDraft: true
                  prerelease: false
